### ISSUE TITLE
UI bombs out if backend unavailable

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#139]
When testing #138 I found that if the backend egeria platform is not active when running the UI, the server will exit.

In a k8s environment this is a glitch, but not fatal, since the pod will get restarted, by which time the platform and/or server will be likely available again.

However it may be worth considering whether to allow the UI to simply report an error to stderr etc, but to tolerate this condition

```
npm run prod                                                    [12:40:41]

> egeria-react-ui-server@2.8.0 prod
> NODE_ENV=production node index.js

Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
Server listening on port: 8091
/login
Error: connect ECONNREFUSED 127.0.0.1:9444
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9444,
  config: {
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    baseURL: 'https://localhost:9444/servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    httpsAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'https:',
      path: '/servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints',
      method: 'GET',
      headers: [Object],
      agent: [Agent],
      agents: [Object],
      auth: undefined,
      hostname: 'localhost',
      port: '9444',
      nativeProtocols: [Object],
      pathname: '/servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: localhost:9444\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: {},
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://localhost:9444/servers/cocoView1/open-metadata/view-services/tex/users/faithbroker/resource-endpoints',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:158:21)
    at /Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/router/routes.js:223:25
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by davidradl** [comment]
@planetf1 I guess this occurs using tex. I suspect that glossary author would recover better; it also has different js error processing and logic to show a connect button to retry the connection in this case.

**Comment by planetf1** [comment]
The original issue reported is now fixed - the UI does not exit, so closing
