### ISSUE TITLE
Improve errors when back end misconfigured (and consider dino/rex rewording)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#81]
If the react UI is run without a properly configured backend 

In REX we see:
<img width="461" alt="Screenshot 2021-02-10 at 10 09 17" src="https://user-images.githubusercontent.com/7292002/107495556-2545fc80-6b88-11eb-97dd-2583770f335d.png">

But in TEX we get:
<img width="469" alt="Screenshot 2021-02-10 at 10 10 52" src="https://user-images.githubusercontent.com/7292002/107495810-77871d80-6b88-11eb-8fa3-c9f6c7a44a3e.png">

Dino is similar with
<img width="461" alt="Screenshot 2021-02-10 at 10 09 17" src="https://user-images.githubusercontent.com/7292002/107495775-6c33f200-6b88-11eb-8958-98956d5cef66.png">

REX could do with having an error message more like TEX. In all cases it would be useful to remove the undefined entry / add some appropriate text

When we look at Glossary Author we have:
<img width="1274" alt="Screenshot 2021-02-10 at 10 13 58" src="https://user-images.githubusercontent.com/7292002/107496017-b61cd800-6b88-11eb-88d0-2eec51745c1f.png">

Which has no information at all (though stdout/stderr shows 'ServerName not configured'

Meanwhile Server author shows no error:
<img width="1205" alt="Screenshot 2021-02-10 at 10 15 25" src="https://user-images.githubusercontent.com/7292002/107496232-f2503880-6b88-11eb-9e6c-70707fff7823.png">

, but stdout/stderr gives:
```
TypeError: Cannot read property 'remoteURL' of undefined
    at /Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/router/routes.js:365:47
    at Layer.handle [as handle_request] (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/index.js:281:22
    at param (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/router/index.js:275:10)

```
More generally having consistency between all elements on the UI

In this case no backend was running & no environment variable was set. Code was master, and a dev build of the react ui was in use.

**Comment by grahamwallis** [comment]
@planetf1 - Did you really want Rex to look more like Tex - I would have thought maybe it was the other way round.

At the core of all of these errors is the error handling by the common module routes.js - which sometimes returns a string and sometimes an object, depending on the specific nature of the problem (i.e. whether it's that a server is not reachable for example vs being reachable but suffering a 400/500 error). Whilst it is possible to handle both cases in the calling UI components, if this aspect of the routes.js were standardised it would help I think.
