### ISSUE TITLE
Server author crashes

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-react-ui#85]
* Started react ui with 'npm start' ie running in dev mode
Default URL is http://localhost:3000, and this is referenced in the README where it says to go to http://localhost:3000/aaa/login - though it also mentions http://localhost:8091/aaa/login - this needs clarification/correction
* Login as garygeeke/admin
* Click Server Author

The following exception is seen on console
```
{
  error: Error: self signed certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1518:34)
      at TLSSocket.emit (node:events:378:20)
      at TLSSocket._finishInit (node:_tls_wrap:942:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:716:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
    config: {
      url: 'https://localhost:9444/open-metadata/platform-services/users/garygeeke/server-platform/servers',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      httpsAgent: [Agent],
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [ClientRequest],
      _currentUrl: 'https://localhost:9444/open-metadata/platform-services/users/garygeeke/server-platform/servers',
      [Symbol(kCapture)]: false
    },
    response: undefined,
    isAxiosError: true,
    toJSON: [Function: toJSON]
  }
}
/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:1123
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'httpsAgent' -> object with constructor 'Agent'
    |     property 'sockets' -> object with constructor 'Object'
    |     ...
    |     property 'errored' -> object with constructor 'Object'
    --- property 'config' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:1123:12)
    at ServerResponse.json (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:260:14)
    at ServerResponse.send (/Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/node_modules/express/lib/response.js:158:21)
    at /Users/jonesn/IdeaProjects/egeria-react-ui/cra-server/router/routes.js:386:23
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Proxy error: Could not proxy request /open-metadata/platform-services/users/garygeeke/server-platform/servers?tenantId=coco from localhost:3000 to https://localhost:8091.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

[nodemon] app crashed - waiting for file changes before starting...

```

At this point the UI is entirely unusable.

The root cause appears to be:
```
  error: Error: self signed certificate
```

This is likely due to incorrect/incomplete cert checking

I will check this with existing certs, and also after updating the base certs

**Comment by planetf1** [comment]
This was also noted testing 2.10 - not just dev mode, but in k8s too

**Comment by davidradl** [comment]
https://github.com/odpi/egeria-react-ui/pull/234 will  fix this.
